## How to get the rank and shape of a tensor

we can use the tf.rank() to get the rank of a tensor.  It is a important to note that 
tf.rank will return a tensor as output, and in order to get the actual value, we will need
to evaluate that tensor.
In addition to the tensor rank, we can also get the shape of a Tensorflow tensor(similar to the shape of a NumPy array). For example, if x is a tensor, we can get its shape using x.get_shape(), which will return an object of a special class called TensorShape. 

In [1]:
import tensorflow as tf

In [5]:
# Check a version of tensorflow
tf.__version__

'1.10.1'

In [6]:
import numpy as np

In [7]:
# declare tf.Graph()
graph = tf.Graph()

In [8]:
with graph.as_default():
    ## define tensors a,b,c use constant
    a = tf.constant(np.pi)
    b = tf.constant([1,2,3,4])
    c = tf.constant([[1,2], [3,4]])   
    ## get their ranks
    r1 = tf.rank(a)
    r2 = tf.rank(b)
    r3 = tf.rank(c)
    ## get their shapes
    s1 = a.get_shape()
    s2 = b.get_shape()
    s3 = c.get_shape()
    print("Shapes: ", s1,s2,s3)

Shapes:  () (4,) (2, 2)


In [11]:
# display rank value
with tf.Session(graph = graph) as sess:
    print("Ranks: ", r1.eval(), r2.eval(), r3.eval())
    
    

Ranks:  0 1 2


In [13]:
# simple example
import tensorflow as tf
hello = tf.constant("Hello, tensorflow")

sess = tf.Session()

a = sess.run(hello)
a.decode("utf-8")

'Hello, tensorflow'

## Understanding TensorFlow's computation graph

In [14]:
import tensorflow as tf

In [15]:
graph = tf.Graph()


In [16]:
with graph.as_default():
    a = tf.constant(1, name = 'a')
    b = tf.constant(2, name = 'b')
    c = tf.constant(3, name = 'c')
    z = 2 * (a-b) + c 

In [17]:
sess = tf.Session(graph=graph)

In [19]:
# Show the graph via tensorboard
writer = tf.summary.FileWriter("/home/unist/first_graph")
# ctrl + alt + t character 

In [20]:
sess.run(z)

1

In [72]:
writer.flush()

In [21]:
writer.close()

In [22]:
sess.close()



if you have pycharm program

on the bottom side 
change to command tab

pip install numpy 
pip install matplotlib
pip install scipy
pip install tensorflow
pip install tensorflow-gpu 
pip install seaborn 
pip install pandas







## Working with TensorFlow’s placeholders, variables, and operations

### Using placeholders for feeding data as input to a model in TensorFlow

#### Defining placeholders

In [23]:
import tensorflow as tf
graph = tf.Graph()
with graph.as_default():
    tf_a = tf.placeholder(tf.int32, shape=[], name = "a")
    tf_b = tf.placeholder(tf.int32, shape=[], name = 'b')
    tf_c = tf.placeholder(tf.int32, shape=[], name = 'c')
    
    r1 = tf_a - tf_b  #1
    r2 = 2 * r1  # 2
    
    z = r2 + tf_c # 3

#### Feeding placeholders with data

In [26]:
## launch the previous graph
with tf.Session(graph=graph) as sess:
    feed = {tf_a:3, tf_b:2, tf_c:1}
    result = sess.run(r2, feed_dict=feed)
    print(result)




2


### Defining placeholders for data arrays with varying batchsizes

Placeholder for varying batchsizes:

In [101]:
import tensorflow as tf
import numpy as np
# process in tensorflow
# 1.build a graph
# 2. feed data and run 
# 3. update your result
graph= tf.Graph()
with graph.as_default():
    tf_x = tf.placeholder(tf.float32, shape=[None, 2], name = "x")
    print(tf_x)
    x_mean = tf.reduce_mean(tf_x, axis=1, name = 'mean')
    # x_sum = tf.reduce_sum(~~~~)
    print(x_mean)

np.random.seed(123)
np.set_printoptions(precision = 2)   # a = 23.4567 --> a = 23.45

with tf.Session(graph=graph) as sess:
    x1 = np.random.uniform(low=0, high=1, size=(5,2))
    print(x1)
    print(x1.shape)
    print(sess.run(x_mean, feed_dict={tf_x:x1}))
    x2 = np.random.uniform(low=0, high=1, size=(10,2))
    print(x2)
    print(x2.shape)
    print(sess.run(x_mean, feed_dict={tf_x:x2}))    
    

Tensor("tf_x:0", shape=(?, 2), dtype=float32)
Tensor("mean:0", shape=(2,), dtype=float32)
[[0.7  0.29]
 [0.23 0.55]
 [0.72 0.42]
 [0.98 0.68]
 [0.48 0.39]]
Feeding data with shape (5, 2)
Result: [0.62 0.47]
[[0.34 0.73]
 [0.44 0.06]
 [0.4  0.74]
 [0.18 0.18]
 [0.53 0.53]
 [0.63 0.85]
 [0.72 0.61]
 [0.72 0.32]
 [0.36 0.23]
 [0.29 0.63]]
Feeding data with shape (10, 2)
Result: [0.46 0.49]


### Variables in TensorFlow


#### Defining Variables

In [27]:
import tensorflow as tf
import numpy as np
graph = tf.Graph()
with graph.as_default():
    w = tf.Variable(np.array([[1,2,3,4], [5,6,7,8]]), name = 'w')
    print(w)




<tf.Variable 'w:0' shape=(2, 4) dtype=int64_ref>


#### Initializing variables

In [28]:
## initialize w and evaluate it
with tf.Session(graph=graph) as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(w))



[[1 2 3 4]
 [5 6 7 8]]


In [94]:
## add the init_op to the graph



## initialize w with init_op and evaluate it





[[1 2 3 4]
 [5 6 7 8]]


In [95]:
graph = tf.Graph()

with graph.as_default():
    w1 = tf.Variable(1, name='w1')
    init_op = tf.global_variables_initializer()
    w2 = tf.Variable(2, name='w2')

In [100]:
# Check the comparison between 'w1' and 'w2'

w2: 1


In [ ]:
#z = w*x + b
import tensorflow as tf
graph = tf.Graph()

with graph.as_default():
    x = tf.placeholder(tf.float32, name='x')
    w = tf.Variable(2.0, name="weight")
    b = tf.Variable(0.7, name = "bias")
    z = w*x + b
    init = tf.global_vaiables_initializer()
with tf.Session(graph=graph) as sess:
    sess.run(init)
    for i in [1.0, 0.6, -1.8]:
        print('x = %4.1f --> z = %4.1f'%(i, sess.run(z, feed_dict={x:i})))
    
   













