In [1]:
from random import choice
from numpy import array, dot, random

In [2]:
unit_step = lambda x: 0 if x < 0 else 1

In [3]:
tr_data = [
    (array([0,0,1]), 0),
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]

In [9]:
w = random.rand(3) # 3 random numbers (0 <= w[i] <= 1)

In [10]:
n = 100 # Number of iterations
eta = 0.2 # Learning rate / alpha

In [11]:
for i in range(n):
    x, expected = choice(tr_data)
    result = dot(w, x)
    error = expected - unit_step(result)
    w += eta * error * x

In [12]:
for x,_ in tr_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:2], result, unit_step(result)))

[0 0]: -0.08520214209732163 -> 0
[0 1]: 0.8533789182242506 -> 1
[1 0]: 0.14361965398237547 -> 1
[1 1]: 1.0822007143039478 -> 1
